'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const luaparse = require('luaparse');
const root = path.resolve(__dirname, '..');
const modules = ['core', 'media', 'preferences', 'components', 'screens', 'content', 'render', 'boot'];
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8').replace(/^\uFEFF/, '').replace(/\r\n/g, '\n').trim();
const manifest = JSON.parse(read('assets/manifest.json'));
const art = Object.entries(manifest).map(([id, asset]) => {
  if (!/^[a-z][a-z0-9_]*$/.test(id) || !asset.frames.length || asset.frames.length > 60) throw new Error('Invalid asset manifest');
  const duration = asset.frames.reduce((sum, frame) => sum + frame.duration, 0);
  const frames = asset.frames.map((frame) => {
    if (!(frame.duration > 0)) throw new Error('Frame duration must be positive');
    const file = path.resolve(root, frame.file);
    if (!file.startsWith(root + path.sep)) throw new Error('Asset must be within project');
    return `{Duration=${frame.duration},Data="${fs.readFileSync(file).toString('base64')}"}`;
  }).join(',\n');
  return `    ${id} = {Width=${asset.width},Height=${asset.height},Duration=${duration},Frames={\n${frames}\n}}`;
}).join(',\n');
const output = '-- DxD UI v1.0.0 | Generated by scripts/build.cjs; edit src/ instead.\n-- See README.md and NOTICE.md for platform requirements and attribution.\nlocal assetData = {\n' + art + '\n}\n\n' + modules.map((name) => `-- ===== ${name}.lua =====\n${read(`src/${name}.lua`)}\n`).join('\n');
luaparse.parse(output, { luaVersion: '5.1' });
fs.writeFileSync(path.join(root, 'dxd.lua'), output);
const sha = crypto.createHash('sha256').update(output).digest('hex');
fs.writeFileSync(path.join(root, 'dxd.lua.sha256'), `${sha}  dxd.lua\n`);
console.log(`Built dxd.lua: ${Buffer.byteLength(output).toLocaleString()} bytes; SHA-256 ${sha}`);
